// KaraokeAlign must pair words and time them exactly as
// shared/karaoke-align.ts does: the same mapping, the same kinds, the same
// timeline.  The fixture is generated by shared/karaoke-align.test.ts.
import XCTest
@testable import CompanionCore

final class KaraokeAlignTests: XCTestCase {
    struct Fixture: Decodable {
        struct Case: Decodable {
            let name: String
            let source: String?
            let spokenText: String
            let displayText: String
            let spokenWords: [Word]
            let displayWords: [Word]
            let guided: Bool
            let spokenToDisplay: [Int]
            let spokenKind: [Int]
            let displayFirstSpoken: [Int]
            let displayLastSpoken: [Int]
            let timeline: [Double]
            /// [spokenContent, spokenMatched, displayContent, displayMatched]
            let quality: [Int]
            let followable: Bool
        }

        /// [start, end, key]
        struct Word: Decodable, Equatable {
            let start: Int
            let end: Int
            let key: String

            init(from decoder: Decoder) throws {
                var c = try decoder.unkeyedContainer()
                start = try c.decode(Int.self)
                end = try c.decode(Int.self)
                key = try c.decode(String.self)
            }

            init(_ word: KaraokeWord) {
                start = word.start
                end = word.end
                key = word.key
            }
        }

        let cases: [Case]
    }

    /// Word i spoken over [i*300, i*300+250), as the fixture assumes.
    private func evenTimes(_ count: Int) -> [Double] {
        (0..<count).flatMap { [Double($0 * 300), Double($0 * 300 + 250)] }
    }

    func testMatchesTheTypeScriptImplementationForEveryFixtureCase() throws {
        let fixture = try SpeechSpansTests.loadFixture("karaoke-align", as: Fixture.self)
        XCTAssertGreaterThan(fixture.cases.count, 10)
        for c in fixture.cases {
            var segments: [SpeechSpan]?
            if let source = c.source {
                let script = SpeechSpans.speakableWithSpans(source)
                XCTAssertEqual(script.text, c.spokenText, "script: \(c.name)")
                segments = script.segments
            }
            let a = KaraokeAlign.alignSpokenToDisplay(
                spokenText: c.spokenText,
                displayText: c.displayText,
                segments: segments,
                sourceText: c.source
            )
            XCTAssertEqual(a.spokenWords.map(Fixture.Word.init), c.spokenWords, "spoken words: \(c.name)")
            XCTAssertEqual(a.displayWords.map(Fixture.Word.init), c.displayWords, "display words: \(c.name)")
            XCTAssertEqual(a.guided, c.guided, "guided: \(c.name)")
            XCTAssertEqual(a.mapping.spokenToDisplay, c.spokenToDisplay, "spokenToDisplay: \(c.name)")
            XCTAssertEqual(a.mapping.spokenKind, c.spokenKind, "spokenKind: \(c.name)")
            XCTAssertEqual(a.mapping.displayFirstSpoken, c.displayFirstSpoken, "displayFirstSpoken: \(c.name)")
            XCTAssertEqual(a.mapping.displayLastSpoken, c.displayLastSpoken, "displayLastSpoken: \(c.name)")
            XCTAssertEqual(
                [a.quality.spokenContent, a.quality.spokenMatched, a.quality.displayContent, a.quality.displayMatched],
                c.quality,
                "quality: \(c.name)"
            )
            XCTAssertEqual(a.followable, c.followable, "followable: \(c.name)")

            let timeline = KaraokeAlign.buildTimeline(spokenTimes: evenTimes(a.spokenWords.count), mapping: a.mapping)
            XCTAssertEqual(timeline.count, c.timeline.count, "timeline length: \(c.name)")
            for (index, (got, want)) in zip(timeline, c.timeline).enumerated() {
                XCTAssertEqual(got, want, accuracy: 1e-6, "timeline[\(index)]: \(c.name)")
            }
        }
    }

    func testNumbersReadAloudLandOnTheirDigits() {
        let a = KaraokeAlign.alignSpokenToDisplay(spokenText: "Flight seven four nine leaves", displayText: "Flight 749 leaves")
        XCTAssertEqual(a.mapping.spokenToDisplay, [0, 1, 1, 1, 2])
        XCTAssertEqual(a.mapping.spokenKind[1], KaraokeAlign.spokenExpanded)
        let b = KaraokeAlign.alignSpokenToDisplay(spokenText: "about twenty-three items", displayText: "about 23 items")
        XCTAssertEqual(b.mapping.spokenToDisplay, [0, 1, 1, 2])
    }

    func testTheFixtureCoversDistilledScriptsAndBriefSummaries() throws {
        let fixture = try SpeechSpansTests.loadFixture("karaoke-align", as: Fixture.self)
        let distilled = fixture.cases.filter { $0.name.hasPrefix("distilled:") }
        XCTAssertGreaterThanOrEqual(distilled.count, 6)
        XCTAssertTrue(distilled.allSatisfy(\.followable))
        let summaries = fixture.cases.filter { $0.name.hasPrefix("brief summary") }
        XCTAssertEqual(summaries.count, 2)
        XCTAssertTrue(summaries.allSatisfy { !$0.followable })
        // A script with spans is followed however little of it pairs.
        let links = try XCTUnwrap(fixture.cases.first { $0.name == "guided link list" })
        XCTAssertTrue(links.guided)
        XCTAssertTrue(links.followable)
        XCTAssertFalse(KaraokeAlign.followable(KaraokeQuality(
            spokenContent: links.quality[0], spokenMatched: links.quality[1],
            displayContent: links.quality[2], displayMatched: links.quality[3]
        )))
        // A code read out one character at a time joins up to 40 characters.
        let atCap = try XCTUnwrap(fixture.cases.first { $0.name == "joined run at the cap" })
        XCTAssertEqual(atCap.spokenKind.filter { $0 == KaraokeAlign.spokenExpanded }.count, 40)
    }

    func testADistilledScriptLandsOnTheRenderedWords() {
        let a = KaraokeAlign.alignSpokenToDisplay(
            spokenText: "Next, issue seven four nine was fixed. <#0.3#> The A P I timeout is three point five seconds.",
            displayText: "Fixed issue #749\nThe API timeout is 3.5 seconds"
        )
        let landed = a.spokenWords.indices.map { i -> String in
            let d = a.mapping.spokenToDisplay[i]
            return d >= 0 ? a.displayWords[d].text : "-"
        }
        let pairs = Dictionary(zip(a.spokenWords.map(\.text), landed), uniquingKeysWith: { first, _ in first })
        XCTAssertEqual(pairs["seven"], "749")
        XCTAssertEqual(pairs["nine"], "749")
        XCTAssertEqual(pairs["A"], "API")
        XCTAssertEqual(pairs["five"], "5")
        XCTAssertFalse(a.spokenWords.contains { $0.text == "0" }, "pause tags are not words")
        XCTAssertTrue(a.followable)
    }

    func testPauseTagsAreBlankedWithoutMovingOffsets() {
        let spoken = "Done. <#0.3#> Next, the tests. <#1.25#> Done."
        XCTAssertEqual((SpokenPause.mask(spoken) as NSString).length, (spoken as NSString).length)
        let a = KaraokeAlign.alignSpokenToDisplay(spokenText: spoken, displayText: "Done.\nThe tests.\nDone.")
        XCTAssertEqual(a.spokenWords.map { (spoken as NSString).substring(with: NSRange(location: $0.start, length: $0.end - $0.start)) },
                       ["Done", "Next", "the", "tests", "Done"])
    }

    func testFollowThresholdsMatchTheTypeScriptRule() {
        XCTAssertTrue(KaraokeAlign.followable(KaraokeQuality(spokenContent: 3, spokenMatched: 1, displayContent: 8, displayMatched: 1)))
        XCTAssertFalse(KaraokeAlign.followable(KaraokeQuality(spokenContent: 4, spokenMatched: 1, displayContent: 8, displayMatched: 1)))
        // How much of the screen is covered is not a bar.
        XCTAssertTrue(KaraokeAlign.followable(KaraokeQuality(spokenContent: 3, spokenMatched: 1, displayContent: 9, displayMatched: 1)))
        XCTAssertTrue(KaraokeAlign.followable(KaraokeQuality(spokenContent: 9, spokenMatched: 6, displayContent: 129, displayMatched: 6)))
        XCTAssertFalse(KaraokeAlign.followable(KaraokeQuality(spokenContent: 0, spokenMatched: 0, displayContent: 0, displayMatched: 0)))
    }

    func testClipTimesSpreadByCharacterOffset() {
        let text = "The tests pass now. I changed two files."
        let utterances = SpeechSpans.utterancesWithSpans(text)
        let words = KaraokeAlign.tokenize(SpeechSpans.speakableWithSpans(text).text)
        let clips = [
            KaraokeClip(spokenStart: utterances[0].spokenStart, spokenEnd: utterances[0].spokenEnd, startMs: 0, durationMs: 1900),
            KaraokeClip(spokenStart: utterances[1].spokenStart, spokenEnd: utterances[1].spokenEnd, startMs: 2000, durationMs: 2000),
        ]
        let times = KaraokeAlign.proportionalWordTimes(words, clips: clips)
        XCTAssertEqual(times[0], 0)
        XCTAssertEqual(times[1], 300, accuracy: 1e-9)
        XCTAssertEqual(times[8], 2000)
        XCTAssertEqual(KaraokeAlign.estimatedClips(utterances, msPerChar: 10).map(\.startMs), [0, 190])
    }

    func testWordIndexForASynthesizerRange() {
        let words = KaraokeAlign.tokenize("Hello there, friend.")
        XCTAssertEqual(KaraokeAlign.wordIndex(atUTF16: 0, in: words), 0)
        XCTAssertEqual(KaraokeAlign.wordIndex(atUTF16: 11, in: words), 2)
        XCTAssertEqual(KaraokeAlign.wordIndex(atUTF16: 19, in: words), -1)
    }
}
