// SpeechSpans must produce exactly what shared/speech-spans.ts produces, which
// in turn is pinned to the server's speakable() and toUtterances().  The
// fixture is generated by shared/speech-spans.test.ts; a rule change on one
// side alone fails here.
import XCTest
@testable import CompanionCore

final class SpeechSpansTests: XCTestCase {
    struct Fixture: Decodable {
        struct Case: Decodable {
            struct Utterance: Decodable {
                let text: String
                let spokenStart: Int
                let spokenEnd: Int
                let segments: [[Int]]
            }

            let name: String
            let input: String
            let text: String
            let segments: [[Int]]
            let utterances: [Utterance]
            let utterances40: [String]
        }

        let cases: [Case]
    }

    static func loadFixture<T: Decodable>(_ name: String, as type: T.Type) throws -> T {
        guard let url = Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures")
            ?? Bundle.module.url(forResource: name, withExtension: "json")
        else {
            XCTFail("missing fixture \(name).json — run UPDATE_SPEECH_FIXTURES=1 vitest on shared/")
            throw CocoaError(.fileNoSuchFile)
        }
        return try JSONDecoder().decode(type, from: Data(contentsOf: url))
    }

    private func compact(_ segments: [SpeechSpan]) -> [[Int]] {
        segments.map { [$0.spokenStart, $0.spokenEnd, $0.srcStart, $0.srcEnd, $0.kind.rawValue] }
    }

    func testMatchesTheTypeScriptImplementationForEveryFixtureCase() throws {
        let fixture = try Self.loadFixture("speech-spans", as: Fixture.self)
        XCTAssertGreaterThan(fixture.cases.count, 50)
        for c in fixture.cases {
            let script = SpeechSpans.speakableWithSpans(c.input)
            XCTAssertEqual(Array(script.text.utf16), Array(c.text.utf16), "text: \(c.name)")
            XCTAssertEqual(compact(script.segments), c.segments, "segments: \(c.name)")

            let utterances = SpeechSpans.utterancesWithSpans(c.input)
            XCTAssertEqual(utterances.map(\.text), c.utterances.map(\.text), "utterances: \(c.name)")
            XCTAssertEqual(utterances.map(\.spokenStart), c.utterances.map(\.spokenStart), "utterance starts: \(c.name)")
            XCTAssertEqual(utterances.map(\.spokenEnd), c.utterances.map(\.spokenEnd), "utterance ends: \(c.name)")
            XCTAssertEqual(utterances.map { compact($0.segments) }, c.utterances.map(\.segments), "utterance spans: \(c.name)")

            XCTAssertEqual(SpeechSpans.utterancesWithSpans(c.input, maxChars: 40).map(\.text), c.utterances40, "max 40: \(c.name)")
        }
    }

    func testCopySpansPointAtTheSameText() {
        let input = "## Plan\n\nRead [the docs](https://x.test/d) then run `pnpm test`. 🚀 Done."
        let script = SpeechSpans.speakableWithSpans(input)
        let spoken = Array(script.text.utf16)
        let source = Array(input.utf16)
        for seg in script.segments where seg.kind == .copy {
            XCTAssertEqual(Array(spoken[seg.spokenStart..<seg.spokenEnd]), Array(source[seg.srcStart..<seg.srcEnd]))
        }
    }

    func testSourceOffsetLandsOnTheWordInTheMessage() {
        let input = "Read [the docs](https://x.test/d) now."
        let script = SpeechSpans.speakableWithSpans(input)
        let spoken = script.text as NSString
        let at = spoken.range(of: "docs").location
        let offset = SpeechSpans.sourceOffset(at: at, in: script.segments)
        XCTAssertEqual((input as NSString).substring(with: NSRange(location: offset, length: 4)), "docs")
    }

    func testUTF16OffsetsConvertToStringAndAttributedRanges() throws {
        let text = "🚀 launch café"
        let range = try XCTUnwrap(SpeechSpans.stringRange(utf16: 3, 9, in: text))
        XCTAssertEqual(String(text[range]), "launch")
        // inside the rocket's surrogate pair is not a position
        XCTAssertNil(SpeechSpans.stringRange(utf16: 1, 3, in: text))
        XCTAssertNil(SpeechSpans.stringRange(utf16: 10, 99, in: text))

        let attributed = AttributedString(text)
        let attributedRange = try XCTUnwrap(SpeechSpans.attributedRange(utf16: 10, 14, in: attributed))
        XCTAssertEqual(String(attributed[attributedRange].characters), "café")
    }
}
